services:
  booking_back_service:
    container_name: "booking_back"
    build:
      context: .
    ports:
      - "7777:8000"
    networks:
      - bookingNetwork
    env_file:
      - .env


  booking_celery_worker_service:
    container_name: "booking_celery_worker"
    build:
      context: .
    networks:
      - bookingNetwork
    env_file:
      - .env
    command: "celery --app=src.connectors.celery_connector:celery_app worker -l INFO"


  booking_celery_beat_service:
    container_name: "booking_celery_beat"
    build:
      context: .
    networks:
      - bookingNetwork
    env_file:
      - .env
    command: "celery --app=src.connectors.celery_connector:celery_app beat -l INFO"


  booking_db:
    image: postgres:17.5-bookworm
    container_name: "booking_database"

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "6432:5432"

    volumes:
      - booking_pg_data:/var/lib/postgresql/data

    networks:
      - bookingNetwork


  redis:
    image: redis:7.4
    container_name: "booking_redis"
    ports:
      - "7379:6379"
    networks:
      - bookingNetwork

volumes:
  booking_pg_data:

networks:
  bookingNetwork:
    driver: bridge